### ISSUE TITLE
Doesn't install in MT 5.0-ja

### ISSUE THREAD

**Issue by vrruiz** [byrnereese/mt-theme-midcentury#2]
Hi. I have a MTOS 5.0-ja installation using ES (Spanish) locale. I installed the plugin and right after the creation of the blog with this template set, MT breaks: "Can't call method "translate" on an undefined value at lib/MT/Component.pm line 559". Does it require MT Pro or is something else?

**Comment by byrnereese** [comment]
Just pushed Mid Century 2.3 which might resolve this problem.
